name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # or main, depending on your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build ./18.0 --file ./18.0/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-image:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest

